name: tenka_modules_template
description: Module template for Tenka
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    intl: ^0.18.0
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    tenka_dev_tools:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka_dev_tools
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
    path: ^1.8.0
